### 分词
#### 最大匹配法【Maximum Matching】MM
最大匹配是指以词典为依据，取词典中最长单词的字数量作为截取词的起始匹配长度，将截取后的最大长度的词与词典中的词进行比对（为提升扫描效率，还可以根据字数多少设计多个字典，然后根据字数分别从不同字典中进行扫描匹配）， 直到还剩一个单字则终止，如果该单字无法切分，则作为未登录词处理（没有被收录在分词词表中但必须切分出来的词，包括各类专有名词（人名、地名、企业名等）、缩写词、新增词汇等等）

栗子：词典中最长词为“中华人民共和国”共7个汉字，则最大匹配起始字数为7个汉字。然后逐字递减，重新在对应的词典中循环比对

#### 正向最大匹配法
从左往右地进行最大匹配法。尽可能地选择与词典中最长单词匹配的词作为目标分词，然后进行下一次匹配

**栗子**
待切分文本 计算语言学课程有意思
词典（表） {"计算", "计算语言学", "课程", "有", "意思"}(真实的词表中会有成千上万个平时我们使用的已经分好的词语)

**匹配过程**
确定最大匹配的起始子串字数为词典中最长单词的长度5
输入 计算语言学课程有意思
第一轮 取子串“计算语言学”，正向取词，如果匹配失败，每次去掉待匹配子串最后面的一个字
第1次. “计算语言学”，扫描词典表，匹配，输出“计算语言学”，输入变为“课程有意思”
第二轮 取子串“课程有意思”
第1次. “课程有意思”， 扫描词典表，不匹配，子串长度减一变为“课程有意”
第2次. “课程有意”， 扫描词典表，不匹配，子串长度减一变为“课程有”
第3次. “课程有”， 扫描词典表，不匹配，子串长度减一变为“课程”
第4次. “课程”， 扫描词典表，匹配，输出“课程”，输入变为“有意思”
第三轮 取子串“有意思”
第1次. “有意思”， 扫描词典表，不匹配，子串长度减一变为“有意”
第2次. “有意”， 扫描词典表，不匹配，子串长度减一变为“有”
第3次. “有”， 扫描词典表，匹配，输出“有”，输入变为“意思”
第四轮 取子串“意思”
第1次. “意思”，扫描词典表，匹配，输出“意思”，输入变为“”
输入长度为零，终止扫描。
最终分词结果为：计算语言学/课程/有/意思

#### 逆向最大匹配算法 RMM
从右往左地进行最大匹配法。尽可能地选择与词典中最长单词匹配的词作为目标分词，然后进行下一次匹配。在实践中，逆向最大匹配算法性能通常优于正向最大匹配算法。

**栗子：**
待切分文本 计算语言学课程有意思
词典（表） {"计算", "计算语言学", "课程", "有", "意思"}(真实的词表中会有成千上万个平时我们使用的已经分好的词语)

**匹配过程**
确定最大匹配的起始子串字数为词典中最长单词的长度5

输入 计算语言学课程有意思

第一轮 取子串“课程有意思”，逆向取词，如果匹配失败，每次去掉待匹配子串最前面的一个字
第1次. “课程有意思”，扫描词典表，不匹配，子串长度减一变为“程有意思”
第2次. “程有意思”，扫描词典表，不匹配，子串长度减一变为“有意思”
第3次. “有意思”，扫描词典表，不匹配，子串长度减一变为“意思”
第4次. “意思”，扫描词典表，匹配，输出“意思”，输入变为“计算语言学课程有”

第二轮 取子串“言学课程有”
第1次. “言学课程有”， 扫描词典表，不匹配，子串长度减一变为“学课程有”
第2次. “学课程有”， 扫描词典表，不匹配，子串长度减一变为“课程有”
第3次. “课程有”， 扫描词典表，不匹配，子串长度减一变为“程有”
第4次. “程有”， 扫描词典表，子串长度减一变为“有”
第5次. “有”， 扫描词典表，匹配，输出“有”，输入变为“计算语言学课程”

第三轮 取子串“语言学课程”
第1次. “语言学课程”， 扫描词典表，不匹配，子串长度减一变为“言学课程”
第2次. “言学课程”， 扫描词典表，不匹配，子串长度减一变为“学课程”
第3次. “学课程”， 扫描词典表，不匹配，子串长度减一变为“课程”
第4次. “课程”， 扫描词典表，匹配，输出“课程”，输入变为“计算语言学”

第四轮 取子串“计算语言学”
第1次. “计算语言学”，扫描词典表，匹配，输出“计算语言学”，输入变为“”
输入长度为零，终止扫描。
最终分词结果为：计算语言学/课程/有/意思

#### 双向最大匹配法
两种算法都切一遍，然后根据大颗粒度词越多越好，非词典词(未登录词)和单字词越少越好的原则，选取其中一种分词结果输出

**算法流程：**
比较正向最大匹配和逆向最大匹配结果
如果分词数量结果不同，那么取分词数量较少的那个
如果分词数量结果相同
3.1 分词结果相同，可以返回任何一个
3.2 分词结果不同，返回单字数比较少的那个

参考：https://www.cnblogs.com/Jm-15/p/9403352.html



语言模型

unigram: 单word

bigram: 双word

trigram: 3 word

**栗子**

西安交通大学：

unigram形式为：西/安/交/通/大/学

bigram形式为： 西安/安交/交通/通大/大学

trigram形式为：西安交/安交通/交通大/通大学

### 分词处理流程

In [ ]:
import jieba as jb
from collections import Counter #统计词频


import numpy as np
import tensorflow.contrib.keras as kr

#### 加载停用词表

In [ ]:
def stopwordslist(stopfile):
    stopwords = [line.strip() for line in open(stopfile, 'r', encoding='utf-8').readlines()]
    return stopwords

#### 读取训练文件，并去除停用词

In [ ]:
def read_file_without_stopwords(filename, stopfile):
    """读取文件数据"""
    contents, labels = [], []
    stopwords = stopwordslist(stopfile)
    with open_file(filename) as f:
        for line in f:
            try:
                label, content = line.replace(' ', '').split('\t')
                if content:
                    rawwords = list(jb.cut(native_content(content)))
                    contents.append([_ for _ in rawwords if _ not in stopwords])
                    labels.append(native_content(label))
            except:
                pass
    return contents, labels

#### 构建词表

In [ ]:
def build_words_table(trainfile, wordsfile, stopfile, vocab_size=5000):
    """根据训练集构建词汇表，存储"""
    data_train, _ = read_file_without_stopwords(trainfile, stopfile)

    all_data = []
    for content in data_train:
        all_data.extend(content)

    counter = Counter(all_data)
    count_pairs = counter.most_common(vocab_size - 1)
    words, _ = list(zip(*count_pairs))
    # 添加一个 <PAD> 来将所有文本pad为同一长度
    words = ['<PAD>'] + list(words)
    open_file(wordsfile, mode='w').write('\n'.join(words) + '\n')
    

#### 加载编码后的词表与种类表

In [ ]:
def read_vocab(vocab_dir):
    """读取词汇表"""
    # words = open_file(vocab_dir).read().strip().split('\n')
    with open_file(vocab_dir) as fp:
        # 如果是py2 则每个值都转化为unicode
        words = [native_content(_.strip()) for _ in fp.readlines()]
    word_to_id = dict(zip(words, range(len(words))))
    return words, word_to_id


def read_category():
    """读取分类目录，固定"""
    categories = ['体育', '财经', '房产', '家居', '教育', '科技', '时尚', '时政', '游戏', '娱乐']

    categories = [native_content(x) for x in categories]

    cat_to_id = dict(zip(categories, range(len(categories))))

    return categories, cat_to_id

#### 文档编码

In [ ]:
def process_file_without_stopwords(filename, stopfile, word_to_id, cat_to_id, max_length=600):
    """将文件转换为id表示"""
    contents, labels = read_file_without_stopwords(filename, stopfile)

    data_id, label_id = [], []
    for i in range(len(contents)):
        data_id.append([word_to_id[x] for x in contents[i] if x in word_to_id])
        label_id.append(cat_to_id[labels[i]])

    # 使用keras提供的pad_sequences来将文本pad为固定长度
    # x_pad = kr.preprocessing.sequence.pad_sequences(data_id, max_length)
    # y_pad = kr.utils.to_categorical(label_id, num_classes=len(cat_to_id))  # 将标签转换为one-hot表示

    return data_id, label_id

#### 文档解码【每个词用/分隔开】

In [ ]:
def to_words(content, words):
    """将id表示的内容转换为文字"""
    return '/'.join(words[x] for x in content)

#### 整个流程

In [ ]:
# 确定各个文件的路径
trainfile = r'E:\desktop\task1\cnews\cnews.train.txt'
wordfile = r'E:\desktop\task1\cnews\cnews.word.dict.txt'
stopfile = r'E:\desktop\task1\cnews\stop.word.txt' 

# 生成词典表
build_words_table(trainfile, wordfile, stopfile)

# 加载词典表与种类表
words, word_to_id = read_vocab(wordfile)
_, cat_to_id = read_category()

# 文档的编码
x_pad, y_pad = process_file_without_stopwords(trainfile, stopfile, word_to_id, cat_to_id)

#查看输出形状
print(x_pad.shape)
print(y_pad.shape)

#一个具体的新闻文本的编码与解码输出
print(x_pad[0])
print(to_words(x_pad[0], words))


### jieba分词 统计词频

In [ ]:
#jieba分词
import jieba.posseg as pseg
import collections

words = pseg.cut("1、支持三种分词模式：(1)精确模式：试图将句子最精确的切开，适合文本分析。(2)全模式：把句子中所有可以成词的词语都扫描出来，速度非常快，但是不能解决歧义。(3)搜索引擎模式：在精确模式的基础上，对长词再次切分，提高召回率，适合用于搜索引擎分词。2、支持繁体分词3、支持自定义词典")
for word in words:
    print (word.word,word.flag)
 

In [ ]:
#词频统计
print("-------------counter word--------------")
import collections
word_counter = collections.Counter([word.text for word in seg_list])

for k,v in word_counter.items():
    print(k,v)

### 文本矩阵化

In [ ]:
#encoding=utf-8
import numpy as np
import jieba
from sklearn.feature_extraction.text import CountVectorizer
 
if __name__ == "__main__":
    count = CountVectorizer()

    docs_list=[]
    mywordlist=[]
    stopwords_path = "resource/stop_words.txt" # 停用词词表

    # 读取文件
    file_object = open('resource/text1.txt','r')
    try:
      for line in file_object:
          # 文本分词
          seg_list = jieba.cut(line, cut_all=False)
          liststr="/ ".join(seg_list)

           # 读取停用词文件
          f_stop = open(stopwords_path,'r', encoding='UTF-8')
          try:
            f_stop_text = f_stop.read()
          finally:
            f_stop.close()

          # 停用词清除
          f_stop_seg_list = f_stop_text.split('\n')
          for myword in liststr.split('/'):
            if not(myword.strip() in f_stop_seg_list) and len(myword.strip())>1:
              mywordlist.append(myword)

          docs_list.append(''.join(mywordlist))      # 存入文档列表中
          mywordlist=[]                  # 存入之后，需要清除mywordlist内容，防止重复
    finally:  
      file_object.close()

    print(f"docs_list:{docs_list}")

    docs = np.array(docs_list)
    print(f"docs:{docs}")
    '''
      output:
      docs_list:[
        '当地 时间 2017 15', '日本 神奈川县 横须贺', 
        ' 东芝 国际 反应堆 报废 研究 开发 机构 IRID 共同开发 机器人 公开 亮相', 
        '这个 30 厘米 直径 13 厘米 水下 机器人 投放 福岛 第一 核电站 机组 反应堆 安全壳 底部 展开 调查'
      ]
    docs:[
      '当地 时间 2017 15' '日本 神奈川县 横须贺'
      ' 东芝 国际 反应堆 报废 研究 开发 机构 IRID 共同开发 机器人 公开 亮相'
      '这个 30 厘米 直径 13 厘米 水下 机器人 投放 福岛 第一 核电站 机组 反应堆 安全壳 底部 展开 调查'
    ]
  '''

    #创建词袋模型的词汇库
    bag = count.fit_transform(docs)
    #查看词汇的位置，词汇是以字典的形式存储
    print(count.vocabulary_)
    '''
      output:
        {'当地': 16, '时间': 20, '2017': 2, '15': 1, '日本': 19, 
        '神奈川县': 29, '横须贺': 25, '东芝': 5, '国际': 11, 
        '反应堆': 10, '报废': 18, '研究': 28, '开发': 15, '机构': 22, 
        'irid': 4, '共同开发': 8, '机器人': 21, '公开': 7, '亮相': 6, 
        '这个': 33, '30': 3, '厘米': 9, '直径': 27, '13': 0, '水下': 26, 
        '投放': 17, '福岛': 30, '第一': 31, '核电站': 24, '机组': 23, 
        '安全壳': 12, '底部': 14, '展开': 13, '调查': 32}
    '''
    print(bag.toarray())
    '''
      output:
        [[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
       [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
       [0 0 0 0 1 1 1 1 1 0 1 1 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0]
       [1 0 0 1 0 0 0 0 0 2 1 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 1 1 1 1]]
    '''